TRUNCATE TABLE IF EXISTS movies;

TRUNCATE TABLE IF EXISTS actors;

TRUNCATE TABLE IF EXISTS genres;

TRUNCATE TABLE IF EXISTS tags;

TRUNCATE TABLE IF EXISTS tag_names;

DROP TABLE IF EXISTS movies;

DROP TABLE IF EXISTS actors;

DROP TABLE IF EXISTS genres;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS tag_names;