TRUNCATE TABLE movies;

TRUNCATE TABLE actors;

TRUNCATE TABLE genres;

TRUNCATE TABLE tags;

TRUNCATE TABLE tag_names;

DROP TABLE IF EXISTS movies CASCADE;

DROP TABLE IF EXISTS actors CASCADE;

DROP TABLE IF EXISTS genres CASCADE;

DROP TABLE IF EXISTS tags CASCADE;

DROP TABLE IF EXISTS tag_names CASCADE;