TRUNCATE TABLE movies;

TRUNCATE TABLE actors;

TRUNCATE TABLE genres;

TRUNCATE TABLE tags;

TRUNCATE TABLE tag_names;

DROP TABLE IF EXISTS movies;

DROP TABLE IF EXISTS actors;

DROP TABLE IF EXISTS genres;

DROP TABLE IF EXISTS tags;

DROP TABLE IF EXISTS tag_names;